name: Push

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install dependencies
        run: |
            sudo pip install ufbt --break-system-packages

      - name: Build
        run: |
            ufbt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: push
          path: dist/blackhat.fap
